name: final_project
channels:
  - conda-forge
dependencies:
  - argparse
  - csv
  - datasets
  - datetime
  - matplotlib
  - nltk
  - numpy
  - pandas
  - pathlib
  - pipeline
  - seaborn
  - sklearn
  - pip:
    - praw
    - emoji
    - torch
    - transformers